{% set name = "reprozip" %}
{% set version = "1.0.12" %}
{% set sha256 = "7525016157c662361e7b1ac0741df1ddffb7be2fae4855ffb087c276c63a7f8c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [not linux32 and not linux64]
  number: 0
  script: "INCLUDE_PATH=${PREFIX}/include C_INCLUDE_PATH=${PREFIX}/include python setup.py install --single-version-externally-managed --record record.txt"

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - sqlite 3.13.*
  run:
    - python
    - setuptools  # for pkg_resources
    - pyyaml
    - requests
    - rpaths >=0.8
    - usagestats >=0.3

test:
  imports:
    - reprozip.main
    - reprozip._pytracer

  commands:
    - reprozip --help

about:
  home: http://github.com/ViDA-NYU/reprozip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Linux tool enabling reproducible experiments (packer)'
  description: |
    ReproZip is a tool aimed at simplifying the process of creating reproducible
    experiments from command-line executions, a frequently-used common
    denominator in computational science. It tracks operating system calls and
    creates a package that contains all the binaries, files and dependencies
    required to run a given command on the author's computational environment
    (packing step). A reviewer can then extract the experiment in his
    environment to reproduce the results (unpacking step).
  doc_url: https://docs.reprozip.org/
  dev_url: https://github.com/ViDA-NYU/reprozip

extra:
  recipe-maintainers:
    - remram44
