{% set name = "reprozip" %}
{% set version = "1.0.14" %}
{% set sha256 = "e0fb2b684951e2c5b27f8e6ca099bba4175d335076b230fe8e523c6041a0c7f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [not linux32 and not linux64]
  number: 1000
  script: "INCLUDE_PATH=${PREFIX}/include C_INCLUDE_PATH=${PREFIX}/include $PYTHON -m pip install --no-deps --ignore-installed . --verbose"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - sqlite
  run:
    - python
    - setuptools  # for pkg_resources
    - pyyaml
    - requests
    - rpaths >=0.8
    - usagestats >=0.3

test:
  imports:
    - reprozip.main
    - reprozip._pytracer

  commands:
    - reprozip --help

about:
  home: http://github.com/ViDA-NYU/reprozip
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Linux tool enabling reproducible experiments (packer)'
  description: |
    ReproZip is a tool aimed at simplifying the process of creating reproducible
    experiments from command-line executions, a frequently-used common
    denominator in computational science. It tracks operating system calls and
    creates a package that contains all the binaries, files and dependencies
    required to run a given command on the author's computational environment
    (packing step). A reviewer can then extract the experiment in his
    environment to reproduce the results (unpacking step).
  doc_url: https://docs.reprozip.org/
  dev_url: https://github.com/ViDA-NYU/reprozip

extra:
  recipe-maintainers:
    - remram44
