appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: T9lvwYfuLrTt6rj8KgJAh/PZGBM7+SYRK5zqeqrzkLPjr24QkB27cXo/iOYa+GrckulxnuZgOoZw7RQXTLC9lyLif4XyKzZ9bJcOf4iHcuALrsH4TM0EN+UNINUK0W36L+Urh0c9Z0STwD/lbKjIKQwuAir3TXvsMwBcHoSuY/WBS7R8ddHaWnbGYhKvjx8OYtBL9QjSwWNVN3+G44cQTtj97E/5hNhPr/yEo9RlIWf3L8HtWV9Ei9uVtoPteSximA3RLBigEnxfHh706q3HLV7ghZoDU0t2c4FHQKNY+kQyoijkYflrAuqO520AIk+GWJqF6l9Bbg5p1uZwdgj2eEE/CkM6fT975XtKc8AHH9HxRIz2RcG7Q/i7lJayBNg8jhWdeuf0Ki9R6n5qrtpqawknlnwP7QxxZhHgFx5B842/34r40umq1oyB1W4yXf0h3jemQAYHnfzW9Kj0OgMGitQc1xItPJKr0LBnRtS19c7elTR8AcOohdro2tK9zAUq3JlxPUu+kSHyqOHGc/P0yUX7nGsOgOtmanIsXJZAvA9QtoQYa0Vta6sfaKu0MZ/FLSHCxa9/rAbHWrRuGi/sZkNhpfkgJYUkLbO3b4d10TdEG39/Vqtvewkx95vS4b0LUFZc38bbj084DwN5IC46vDJZYNC8yA9/b9tBgxS85p8=}
conda_forge_output_validation: false
