travis:
  secure:
    BINSTAR_TOKEN: k+QC14xZwD/1tyiIt78HIRUioNkCla4rLhwHmbg+SoEwcplZ1yrdhzIQEv4pINiD9gtoZdTg+sDocAIPG5oCmswSRh6T1xrccdtsm0fd0Xc1ZtjaRqXToyInjdEjBjmn3SL5THsQzJw+9WvyvZfvESfvoWmvzm/bMy2PboxyIgPeW8zwA0c+m0yh9IHvVJUA36o67Yc1QcPApfnRBtS/jlzDNSk2g8ARD4AULvEsAl1Jf0K3FQAjmCqHVNvwJbzOrnxjVKxFyTgGnmmGkU9ONt5LU+R04DAvnN5TY5yBYDnfpeEpyHHjKDLIqJTR6tzECx9FJUY7SgrHArOBWJkTo1jIju9oKpWI2a/nTzs2ZXA4NO04958+GaynKs66NqkyWrlr/6usME94JH1j4EK2xiOPo3CSaHTKJxL7fR5yNL61mgJbqeTH9vAcfEgfgh2Y4By3vVCsJe4OvoQ5Neyz6nbzhwfJM8v0SQYrLOCRjfrlbgqKUHA9E7TB3pBmD3GD41HNKW4RIrdFSqV+bx3CzEr2b1dC4KkPBIaLIUu6YoEe3pnLq0JfZeKBovKFbM1a+HIEUSiv356oC9qTKgz6zzoUq9USyPds/qS9H7DxviH/b/BR8W0u9+5fQ8rvV/B0F19Q6nrtP33WV7qLewcGZt5GBF2ouv6w5EieaWBmpJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
